PPPK_Movies/MovieActor/MovieActor/Controllers/ActorController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieActor.Controllers
{
    public class ActorController : Controller
    {
        ~ActorController()
        {
            if (db != null)
            {
                db.Dispose();
            }
        }
        private readonly ModelContainer db = new ModelContainer();

        // GET: Actor
        public ActionResult ActorIndex()
        {
            return View(db.Actors);
        }

        // GET: Actor/Details/5
        public ActionResult DetailsActor(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.SingleOrDefault(a => a.IDActor == id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // GET: Actor/Create
        public ActionResult CreateActor()
        {
            return View();
        }

        // POST: Actor/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "FirstName, LastName, MovieIDMovie")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                db.Actors.Add(actor);
                db.SaveChanges();
            }
            return RedirectToAction("ActorIndex");
        }

        // GET: Actor/Edit/5
        public ActionResult EditActor(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors
                .SingleOrDefault(a => a.IDActor == id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // POST: Actor/Edit/5
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditConfirmed()
        {
            Actor movieToUpdate = db.Actors.FirstOrDefault();
            if (TryUpdateModel(movieToUpdate, "",
                new string[] { "FirstName", "LastName", "MovieIDMovie" }))
            {
                db.Entry(movieToUpdate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ActorIndex");
            }
            return View(movieToUpdate);
        }

        // GET: Actor/Delete/5
        public ActionResult DeleteActor(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Actor actor = db.Actors.SingleOrDefault(a => a.IDActor == id);
            if (actor == null)
            {
                return HttpNotFound();
            }
            return View(actor);
        }

        // POST: Actor/Delete/5
        [HttpPost]
        [ActionName("DeleteActor")]
        public ActionResult Delete(int id, FormCollection collection)
        {
            db.Actors.Remove(db.Actors.Find(id));
            db.SaveChanges();
            return RedirectToAction("ActorIndex");
        }
    }
}

PPPK_Movies/MovieActor/MovieActor/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieActor.Controllers
{
    public class FilesController : Controller
    {
        ~FilesController()
        {
            if (db != null)
            {
                db.Dispose();
            }
        }
        private readonly ModelContainer db = new ModelContainer();
        // GET: Files
        public ActionResult Index(int id)
        {
            var uploadedFile = db.UploadedFiles.Find(id);
            return File(uploadedFile.Content, uploadedFile.ContentType);
        }
        public ActionResult Delete(int id)
        {
            db.UploadedFiles.Remove(db.UploadedFiles.Find(id));
            db.SaveChanges();
            return Redirect(Request.UrlReferrer.AbsolutePath);
        }
    }
}

PPPK_Movies/MovieActor/MovieActor/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MovieActor.Controllers
{
    public class MovieController : Controller
    {
        ~MovieController()
        {
            if (db != null)
            {
                db.Dispose();
            }
        }
        private readonly ModelContainer db = new ModelContainer();
        // GET: Movie
        public ActionResult Index()
        {
            return View(db.Movies);
        }

        // GET: Movie/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Include(a => a.UploadedFiles)
                .SingleOrDefault(a => a.IDMovie == id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: Movie/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Movie/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "Name, YearOfRelease")] Movie movie,
            IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid)
            {
                movie.UploadedFiles = new List<UploadedFile>();
                foreach (var file in files)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        var picture = new UploadedFile
                        {
                            Name = System.IO.Path.GetFileName(file.FileName),
                            ContentType = file.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(file.InputStream))
                        {
                            picture.Content = reader.ReadBytes(file.ContentLength);
                        }
                        movie.UploadedFiles.Add(picture);
                    }
                }

                db.Movies.Add(movie);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        // GET: Movie/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies
                .Include(a => a.UploadedFiles)
                .SingleOrDefault(a => a.IDMovie == id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movie/Edit/5
        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditConfirmed(int id, IEnumerable<HttpPostedFileBase> files)
        {
            Movie movieToUpdate = db.Movies.Find(id);
            if (TryUpdateModel(movieToUpdate, "",
                new string[] { "Name", "YearOfRelease" }))
            {
                if (movieToUpdate.UploadedFiles == null)
                {
                    movieToUpdate.UploadedFiles = new List<UploadedFile>();
                }
                foreach (var file in files)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        var picture = new UploadedFile
                        {
                            Name = System.IO.Path.GetFileName(file.FileName),
                            ContentType = file.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(file.InputStream))
                        {
                            picture.Content = reader.ReadBytes(file.ContentLength);
                        }
                        movieToUpdate.UploadedFiles.Add(picture);
                    }
                }

                db.Entry(movieToUpdate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movieToUpdate);
        }

        // GET: Movie/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies
                .Include(a => a.UploadedFiles)
                .SingleOrDefault(a => a.IDMovie == id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movie/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            db.UploadedFiles.RemoveRange(db.UploadedFiles.Where(f => f.MovieIDMovie == id));
            db.Movies.Remove(db.Movies.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PPPK_Movies/MovieActor/MovieActor/Views/Movie/Create.cshtml
@model MovieActor.Movie

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Movie", null, FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Movie</h4>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YearOfRelease, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YearOfRelease, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YearOfRelease, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Picture", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="Picture" multiple accept="image/*" name="files" />
        </div>
    </div>      

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PPPK_Movies/MovieActor/MovieActor/Views/Movie/Delete.cshtml
@model MovieActor.Movie

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDMovie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDMovie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearOfRelease)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearOfRelease)
        </dd>

        @foreach (var actor in Model.Actors)
        {
            <dd> @actor.FirstName @actor.LastName </dd>
        }

        @foreach (var uploadedFile in Model.UploadedFiles)
        {
            <dt>
                @uploadedFile.Name
            </dt>

            <dd style="margin-top:10px">
                <img src="~/Files?id=@uploadedFile.IDUploadedFile" alt="picture" width="300" height="200" />
            </dd>
        }

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PPPK_Movies/MovieActor/MovieActor/Views/Movie/Details.cshtml
@model MovieActor.Movie

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IDMovie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IDMovie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearOfRelease)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearOfRelease)
        </dd>

        <dt>Actors:</dt>

        @foreach (var actor in Model.Actors)
        {
            <dd> @actor.FirstName @actor.LastName </dd>
        }


        @foreach (var uploadedFile in Model.UploadedFiles)
        {
            <dt>
                @uploadedFile.Name
            </dt>

            <dd style="margin-top:10px">
                <img src="~/Files?id=@uploadedFile.IDUploadedFile" alt="picture" width="300" height="200" />
            </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDMovie }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PPPK_Movies/MovieActor/MovieActor/Views/Movie/Edit.cshtml
@model MovieActor.Movie

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Movie", null, FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Movie</h4>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.IDMovie, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IDMovie, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.YearOfRelease, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.YearOfRelease, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.YearOfRelease, "", new { @class = "text-danger" })
        </div>
    </div>

    @foreach (var actor in Model.Actors)
    {
        <div class="form-group">
            <span class="control-label col-md-2">
                <Strong>@actor.FirstName @actor.LastName</Strong><br />
                @Ajax.ActionLink("Delete", "DeleteActor", "Actor",
                new { id = actor.IDActor },
                new AjaxOptions { HttpMethod = "Post" })
            </span>
        </div>
    }

    @foreach (var uploadedFile in Model.UploadedFiles)
    {
        <div class="form-group">
            <span class="control-label col-md-2">
                <Strong>@uploadedFile.Name</Strong><br />
                @Ajax.ActionLink("Delete", "Delete", "Files",
            new { id = uploadedFile.IDUploadedFile },
            new AjaxOptions { HttpMethod = "Post" })
            </span>
            <div class="col-md-10">
                <img src="~/Files?id=@uploadedFile.IDUploadedFile" alt="picture" width="300" height="200" />
            </div>
        </div>
    }

    <div class="form-group">
        @Html.Label("Picture", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" id="Picture" multiple accept="image/*" name="files" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PPPK_Movies/MovieActor/MovieActor/Views/Movie/Index.cshtml
@model IEnumerable<MovieActor.Movie>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>

<p>
    @Html.ActionLink("Create New Movie", "Create")

    @Html.ActionLink("Actor", "ActorIndex", "Actor")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IDMovie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.YearOfRelease)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IDMovie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.YearOfRelease)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.IDMovie }) |
            @Html.ActionLink("Details", "Details", new { id = item.IDMovie }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.IDMovie })
        </td>
    </tr>
}

</table>